### ISSUE TITLE
npmのバージョンアップ

### ISSUE THREAD

**Issue by Yukarion** [Yukarion/omu_brasspage#58]
## Why
一生放置していたらnpmパッケージが太古のものとなってしまっていた．現状だと脆弱性になりかねないので修正

## Do
- npmパッケージの中で古くなっているものをリストアップ
- 問題があるnpmパッケージをバージョンアップ
- 動作チェックし問題がないことを確認した上でマージ

**Comment by Melonps** [comment]
discordで言った通り、webpack+vueだとNPMの依存関係のエラー解消に苦戦すると思う。
Viteを使用して依存関係を簡単に解決するのが良いと思うので、やってみます。
